### ISSUE TITLE
Door blocks are not removed correctly

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [MCHPR/MCHPRS#64] opened 2022-05-14 16:19 UTC
When a door is placed, the lower half is removed but not the upper half.
Beds do not exhibit the same bug.

**Comment by AL1L** [comment] 2022-09-18 23:44
Just implement doors lol

**Comment by StackDoubleFlow** [comment] 2024-08-19 02:17
Cannot reproduce on latest, assuming fixed now

**Closed as completed by StackDoubleFlow** 2024-08-19 02:17 UTC
Labels: bug
